branches:
  only:
  - master
  - /^[0-9.]+-releases$/

sudo: required

install:
  - sudo apt-get update -q
  - sudo apt-get install -q linux-headers-$(uname -r) --fix-missing
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.deb
  - sudo dpkg -i vagrant_2.2.4_x86_64.deb

script:
  - VBoxManage --version
  - vagrant box add -f --provider virtualbox hashicorp/precise64
  - vagrant up
  - cd deb/openmediavault
  - fakeroot debian/rules clean binary

addons:
  apt:
    packages:
    - build-essential
    - dh-make
    - dpkg-dev
    - nfs-kernel-server
    - fakeroot
    - git
    - virtualbox
    - virtualbox-dkms
    - linux-headers-generic
