branches:
  only:
  - master
  - /^[0-9.]+-releases$/

sudo: required

install:
  - sudo apt-get update -q
  - sudo apt-get install nfs-kernel-server
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.deb
  - sudo dpkg -i vagrant_2.2.4_x86_64.deb
  - bundle install

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
