branches:
  only:
  - master
  - /^[0-9.]+-releases$/

sudo: required
dist: trusty

install:
  - sudo apt-get update -q
  - sudo apt-get install -q linux-headers-$(uname -r) --fix-missing
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.deb
  - sudo dpkg -i vagrant_2.2.4_x86_64.deb
#  - sudo dpkg-reconfigure virtualbox-dkms
#  - sudo dpkg-reconfigure virtualbox
  - sudo modprobe vboxdrv
  - sudo modprobe vboxnetflt

script:
  - vagrant box add -f --provider virtualbox hashicorp/precise64
  - VBoxManage --version
  - cd vagrant
  - vagrant up
  - cd ../deb/openmediavault
#  - dh-systems debuild -S -sa
  - fakeroot debian/rules clean binary

addons:
  apt:
    packages:
    - build-essential
    - dh-systemd
    - dh-make
    - dh-autoreconf
    - debhelper
    - devscripts
    - dpkg-dev
    - nfs-kernel-server
    - fakeroot
    - git
    - virtualbox
    - virtualbox-dkms
    - linux-headers-generic
