branches:
  only:
  - master
  - /^[0-9.]+-releases$/

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - dh-systemd
    - dh-make
    - dh-autoreconf
#    - debhelper
    - devscripts
    - dpkg-dev
    - nfs-kernel-server
    - fakeroot
    - git
    - virtualbox
    - virtualbox-dkms
    - linux-headers-generic

install:
  - sudo apt-get update -q
  - sudo apt-get install -q linux-headers-$(uname -r) --fix-missing
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.deb
  - sudo dpkg -i vagrant_2.2.4_x86_64.deb
  - sudo dpkg-reconfigure virtualbox-dkms
  - sudo dpkg-reconfigure virtualbox
  - sudo modprobe vboxdrv
  - sudo modprobe vboxnetflt

#jobs:  
#  include:
#    - stage: test
#      name: "Test Vagrant"
#      script: cd && VBoxManage --version && cd vagrant && vagrant up
#    - stage: test
#      name: "Test deb/openmediavault"
#      script: cd && cd deb/openmediavault && fakeroot debian/rules clean binary

script:
  - VBoxManage --version
#  - cd vagrant
#  - vagrant up
  - cd deb/openmediavault
  - fakeroot debian/rules clean binary
